# Model
# model_name: ./hugging_cache/llama-2-7b
# model_name: "./scr/models--meta-llama--Llama-2-7b-hf/snapshots/01c7f73d771dfac7d292323805ebc428287df4f9"
model_name: "./scr/models--locuslab--tofu_ft_llama2-7b/snapshots/8fa500e8f345f1dd9cfe95bb4689878c944c9cbd"
model_class: LlamaForCausalLM
# small_name: ./hugging_cache/llama-160m
small_name: "./scr/models--Cheng98--llama-160m/snapshots/aa9998f9aab075589dd4836d903b26501e549e2e"
# this model caused gradient error: https://github.com/zjunlp/EasyEdit/issues/123
# "./scr/models--JackFram--llama-160m/snapshots/aca9b687d1425f863dcf5de9a4c96e3fe36266dd"
tokenizer_class: LlamaTokenizer
# tokenizer_name: ./hugging_cache/llama-2-7b
# tokenizer_name: "./scr/models--meta-llama--Llama-2-7b-hf/snapshots/01c7f73d771dfac7d292323805ebc428287df4f9"
tokenizer_name: "./scr/models--locuslab--tofu_ft_llama2-7b/snapshots/8fa500e8f345f1dd9cfe95bb4689878c944c9cbd"
# cls_name: ./hugging_cache/distilbert-base-cased
cls_name: "./scr/models--distilbert--distilbert-base-cased/snapshots/6ea81172465e8b0ad3fddeed32b986cdcdcffcf0"
cls_class: AutoModel
inner_params: []
# model_parallel: false
model_parallel: true

archive: null

# Method
alg: SERAC
lr: 1e-5
edit_lr: 1e-2
seed: 0
lr_lr: 0.0
cedit: 0.1
cloc: 1.0
cbase: 1.0
dropout: 0.0
final_eval: True
supervised: False
train_base: False
no_grad_layers: null
soft_weighting: False
checkpoint_grad: False
cross_attend: False
cos: False
freeze: null
square: True
bound_embeds: False
use_all_negatives: False
freeze_cntr: False
dist_heads: 1
lora: null

device: cuda:0
batch_size: 10
model_save_pt: 1000
edit_bs: 1
silent: False
#max_epochs: 1
max_iters: 100000
log_interval: 1000
val_interval: 1000
early_stop_patience: 30000
early_stop_key: "edit/acc_val"
eval_only: False
half: False
# save: False
save: True
debug: False
log_errors: False
unlikelihood: True


val_batch_size: 1
accumulate_bs: 10
val_steps: 1000
opt: Adam
grad_clip: 100.

# Output
# results_dir: ./results
results_dir: ./outputs